services:
  db:
    container_name: postgresql
    image: postgres:13
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=ventas
    ports:
      - 5432:5432
